name = "uunn"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "uunn-production"
database_id = "f93cb9b3-833d-4c48-993a-49e7380c9091"
